### ISSUE TITLE
[Error] Analyzing sketch 'examples\Basic-Read-Write\Basic-Read-Write.ino'

### ISSUE THREAD

**Issue by neo880** [kittyboy2005/AT24C16#5]
hi master
i just try to compile your code, and see this issue happen:

C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp: In member function 'void AT24C16::Erase(uint16_t*, uint8_t*, bool*)':
C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp:148:23: error: invalid conversion from 'const uint8_t*' {aka 'const unsigned char*'} to 'uint8_t*' {aka 'unsigned char*'} [-fpermissive]
  148 |       writeBuffer_(i, Empty_buffer, ROM_PAGE_SIZE);
      |                       ^~~~~~~~~~~~
      |                       |
|                       const uint8_t* {aka const unsigned char*}
C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp:92:55: note:   initializing argument 2 of 'void AT24C16::writeBuffer_(unsigned int, uint8_t*, uint8_t)'
92 | void AT24C16::writeBuffer_(unsigned address, uint8_t* data, uint8_t length) // write buffer (no verify). [Internal Function]
      |                                              ~~~~~~~~~^~~~
C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp: In member function 'bool AT24C16::Erase()':
C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp:188:23: error: invalid conversion from 'const byte*' {aka 'const unsigned char*'} to 'uint8_t*' {aka 'unsigned char*'} [-fpermissive]
  188 |       writeBuffer_(i, Empty_buffer, ROM_PAGE_SIZE);
|                       ^~~~~~~~~~~~
      |                       |
|                       const byte* {aka const unsigned char*}
C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp:92:55: note:   initializing argument 2 of 'void AT24C16::writeBuffer_(unsigned int, uint8_t*, uint8_t)'
92 | void AT24C16::writeBuffer_(unsigned address, uint8_t* data, uint8_t length) // write buffer (no verify). [Internal Function]
|                                              ~~~~~~~~~^~~~
C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp: In member function 'void AT24C16::writeStr(unsigned int, String)':
C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp:353:26: error: invalid conversion from 'char*' to 'uint8_t*' {aka 'unsigned char*'} [-fpermissive]
  353 |   updateBuffer_(address, buffer, len);
      |                          ^~~~~~
      |                          |
      |                          char*
C:\Users\Neo\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.2.0\libraries\AT24C16\AT24C16.cpp:106:56: note:   initializing argument 2 of 'void AT24C16::updateBuffer_(unsigned int, uint8_t*, uint8_t)'
106 | void AT24C16::updateBuffer_(unsigned address, uint8_t* data, uint8_t length) // update buffer [Internal Function]
|                                               ~~~~~~~~~^~~~
exit status 1
IntelliSense configuration already up to date. To manually rebuild your IntelliSense configuration run "Ctrl+Alt+I"
[Error] Analyzing sketch 'examples\Basic-Read-Write\Basic-Read-Write.ino': Exit with code=1

can you give me some hints?
BTW, i'm compile it under VScode + arduino

thx very much

neo

**Comment by manzarehassin** [comment]
Please reinstall the library again
